imports:
    - { resource: ../config_dev.yml }

parameters:
    email: pflieger.arnaud@gmail.com
    database_host:      bjepv58pltdf9ck-postgresql.services.clever-cloud.com
    database_port:      5432
    database_user:      uuw7v8llzr7kpo7chxef
    database_password:  dHZOh1k7CSacvWf3juqU
    database_name:      bjepv58pltdf9ck
