imports:
    - { resource: ../config_test.yml }

parameters:
    database_host:      bjxuzrnkxm1vmht-postgresql.services.clever-cloud.com
    database_port:      5432
    database_user:      umoz70nh6rpvf2phr8wj
    database_password:  GnaHigAJt7qWfMXAKKWp
    database_name:      bjxuzrnkxm1vmht
