imports:
    - { resource: ../config_test.yml }

parameters:
    database_host:      bgksiwshm4i5a0y-postgresql.services.clever-cloud.com
    database_port:      5432
    database_user:      u6xo2i1omq76korpkjd3
    database_password:  grq2qvCHlUE13IN7B1Wx
    database_name:      bgksiwshm4i5a0y
