imports:
    - { resource: ../config_dev.yml }

parameters:
    database_host: bxceyc6zx.mysql.clvrcld.net
    database_port: 3306
    database_user: ujtbevdp9dmenbs8
    database_password: l3KE8J7CBdzbtwYRpCE
    database_name: bxceyc6zx
