imports:
    - { resource: ../config_test.yml }

parameters:
    database_host:      bosdygayz.mysql.clvrcld.net
    database_port:      3306
    database_user:      ukmvrvs2sjgiy8rm
    database_password:  6ZuWhE3syOgUL7DIKw7
    database_name:      bosdygayz
