imports:
    - { resource: ../config_dev.yml }

parameters:
    email: MehdiBelkacemi@gmail.com
    database_host:      bhyljnnbnx3yall-postgresql.services.clever-cloud.com
    database_port:      5432
    database_user:      u3rozrbguxuejto5ch7n
    database_password:  HRhxmRM8pJ8BmkelVjYb
    database_name:      bhyljnnbnx3yall
