imports:
    - { resource: ../config_dev.yml }

parameters:
    database_host: bcygbupac.mysql.clvrcld.net
    database_port: 3306
    database_user: ued2mjrtiqcsxu1r
    database_password: z5a6dveLBVVmNwSeBy9
    database_name: bcygbupac
