imports:
    - { resource: ../config_test.yml }

parameters:
    database_host:      be4bmuekx.mysql.clvrcld.net
    database_port:      3306
    database_user:      ugdd1nzt7dguucwa
    database_password:  sbwJOws7aFKJlphIIcb
    database_name:      be4bmuekx
