imports:
    - { resource: ../config_dev.yml }

parameters:
    email: MehdiBelkacemi@gmail.com
    database_host:      bgnvntqpm.mysql.clvrcld.net
    database_port:      3306
    database_user:      utlr1temuvkvfk6p
    database_password:  eho658B69NqxH0XbVW4
    database_name:      bgnvntqpm
