imports:
    - { resource: ../config_test.yml }

parameters:
    database_host: bymltp3xd.mysql.clvrcld.net
    database_port: 3306
    database_user: u7tqpkd9rnpsrhnj
    database_password: a3RsC6ts8Kk7MrWzRFU
    database_name: bymltp3xd
