imports:
    - { resource: ../config_dev.yml }

parameters:
    email: pflieger.arnaud@gmail.com
    database_host:      bxwpq0tjz.mysql.clvrcld.net
    database_port:      3306
    database_user:      ujon1ijwj3cgymbg
    database_password:  JjaxjLTcC9Q0Lo3glEi
    database_name:      bxwpq0tjz
