language: php
php:
    - '7.0'

services:
    - postgresql

env:
    - SYMFONY_USER=travis

before_install:
    - pip install --user codecov

before_install:
    - pip install --user codecov

install:
    - composer install
    - php app/console doctrine:database:create --env=test
    - php app/console doctrine:schema:create --env=test

script:
    - bin/phpunit --coverage-clover=coverage.xml

after_success:
    - codecov

cache:
    directories:
        - bin
        - node_modules
        - vendor
