imports:
    - { resource: environment.php }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: serializer.yml }

framework:
    secret: 9QoQ5x6SCAQgVcOiINrKaroJF8ZqriAt
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    translator:
        logging: false
    default_locale: fr
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~

monolog:
    handlers:
        syslog:
            type: syslog
            level: NOTICE
        file:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            channels: ["!event"]
            level: DEBUG
            include_stacktraces: true
        mail:
            type:         fingers_crossed
            action_level: ERROR
            handler:      buffer
        buffer:
            type:         buffer
            handler:      swift
        swift:
            type:         swift_mailer
            from_email:   "logs@zigotoo.com"
            to_email:     ["pflieger.arnaud@gmail.com", "MehdiBelkacemi@gmail.com"]
            subject:      "Alerte %kernel.environment% %kernel.user% - %%message%%"
            level:        DEBUG
            include_stacktraces: true
        console_normal:
            type:   console
            bubble: false
            include_stacktraces: true
            verbosity_levels:
                VERBOSITY_NORMAL:       NOTICE
                VERBOSITY_VERBOSE:      INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!event"]
        console_debug:
            include_stacktraces: true
            type:   console
            bubble: false
            # channels: ["event"]
            # ce channel est sous entendu de par la conf "!event" de console_normal
            # On ne peut cependant pas le mettre car en environnement SYMFONY_DEBUG=0,
            # le channel n'existe pas.

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        user:     "%database_user%"
        password: "%database_password%"
        dbname:   "%database_name%"
        charset:  UTF8
        types:
            photoarray: AppBundle\Entity\PhotoArrayType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

jms_serializer:
    handlers:
        datetime:
            default_format: 'Y-m-d\TH:i:s.uO' # https://github.com/schmittjoh/JMSSerializerBundle/issues/395

swiftmailer:
    transport:  smtp
    host:       mail.gandi.net
    username:   app@zigotoo.com
    password:   tatouine1
    encryption: ssl
    spool:      { type: memory }

fos_user:
    db_driver: orm
    firewall_name: fos_user
    user_class: AppBundle\Entity\User
    from_email:
        address:        noreply@zigotoo.com
        sender_name:    Zigotoo