imports:
    - { resource: config.yml }

framework:
    trusted_hosts: "*.zigoto.*"

parameters:
    database_host: ~
    database_port: ~
    database_user: ~
    database_password: ~
    database_name: ~

monolog:
    handlers:
        file: ~
        syslog:
            type:  syslog
            level: NOTICE