imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
    profiler:
        enabled: true

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        file:
            level:  DEBUG
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: true

swiftmailer:
    delivery_address: "%email%" # redirige tous les envois de mails vers cette adresse

jms_serializer:
    visitors:
        json:
            options: JSON_PRETTY_PRINT # indentation du json collé dans le html