imports:
    - { resource: config.yml }

framework:
    test: true
    session:
        storage_id: session.storage.mock_file
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"

swiftmailer:
    disable_delivery: true # désactive, entre autres, l'envoi du mail de logs d'erreur

security:
    encoders:
            # Les tests s'exécutent beaucoup plus vide sans le cryptage des mots de passe
            FOS\UserBundle\Model\UserInterface: plaintext
    firewalls:
        fos:
            form_login: false
            http_basic: true

jms_serializer:
    visitors:
        json:
            options: JSON_PRETTY_PRINT # indentation du json collé dans le html