imports:
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: serializer.yml }

framework:
    secret: 9QoQ5x6SCAQgVcOiINrKaroJF8ZqriAt
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: fr
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~

monolog:
    handlers:
        file:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            channels: ["!event"]
        mail:
            type:         fingers_crossed
            action_level: ERROR
            handler:      buffer
        buffer:
            type:         buffer
            handler:      swift
        swift:
            type:         swift_mailer
            from_email:   "logs@zigoto.com"
            to_email:     ["pflieger.arnaud@gmail.com", "MehdiBelkacemi@gmail.com"]
            subject:      "Alerte %kernel.environment%"
            level:        DEBUG
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        user:     "%database_user%"
        password: "%database_password%"
        dbname:   "%database_name%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

swiftmailer:
    transport: smtp
    host:      127.0.0.1
    username:  null
    password:  null
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: fos
    user_class: AppBundle\Entity\User