imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    encoders:
            # Les tests s'exécutent beaucoup plus vide sans le cryptage des mots de passe
            FOS\UserBundle\Model\UserInterface: plaintext
    firewalls:
        fos:
            form_login: false
            http_basic: true