imports:
    - { resource: config.yml }

framework:
    #trusted_hosts: "*.zigoto.*"

parameters:
    database_host:     bnv8ka2pf.mysql.clvrcld.net
    database_port:     3306
    database_user:     u2afmrzpetvq5lv7
    database_password: pOsHgxUw0HvmETR3OaH
    database_name:     bnv8ka2pf

monolog:
    handlers:
        file: ~
        syslog:
            type:  syslog
            level: NOTICE