imports:
    - { resource: config.yml }

framework:
    trusted_hosts: "*.zigoto.*"

parameters:
    database_host: ~
    database_port: ~
    database_user: ~
    database_password: ~
    database_name: ~

monolog:
    handlers:
        syslog:
            type:  syslog
            level: NOTICE
        mail:
            type:         fingers_crossed
            action_level: ERROR
            handler:      buffered
        buffered:
            type:         buffer
            handler:      swift
        swift:
            type:         swift_mailer
            from_email:   "logs@zigoto.com"
            to_email:     ["pflieger.arnaud@gmail.com", "MehdiBelkacemi@gmail.com"]
            subject:      "Alerte %kernel.environment%"
            level:        DEBUG