services:
    zigotoo.page_eleveur:
        class: AppBundle\Service\PageEleveurService
        arguments:
            - @doctrine.orm.entity_manager
            - @=service('doctrine.orm.entity_manager').getRepository('AppBundle:PageEleveurBranch')
            - @=service('doctrine.orm.entity_manager').getRepository('AppBundle:PageAnimalBranch')
            - @=service('doctrine.orm.entity_manager').getRepository('AppBundle:PageEleveurCommit')
            - @logger

    zigotoo.page_animal:
        class: AppBundle\Service\PageAnimalService
        arguments:
            - @doctrine.orm.entity_manager
            - @=service('doctrine.orm.entity_manager').getRepository('AppBundle:PageAnimalBranch')
            - @file_locator
