services:
    zigotoo.default_controller:
        class: AppBundle\Controller\DefaultController
        arguments:
            - "@security.token_storage"
            - "@templating"
            - "@form.factory"
            - "@router"
            - "@zigotoo.page_eleveur"

    zigotoo.quisommesnous_controller:
        class: AppBundle\Controller\QuiSommesNousController
        arguments:
            - "@templating"

    zigotoo.page_eleveur_controller:
        class: AppBundle\Controller\PageEleveurController
        arguments:
            - "@security.token_storage"
            - "@templating"
            - "@serializer"
            - "@zigotoo.page_eleveur"
            - "@zigotoo.page_animal"

    zigotoo.page_animal_controller:
        class: AppBundle\Controller\PageAnimalController
        arguments:
            - "@templating"
            - "@zigotoo.page_animal"

    zigotoo.page_eleveur:
        class: AppBundle\Service\PageEleveurService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:PageEleveurBranch')"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:PageAnimalBranch')"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:PageEleveurCommit')"
            - "@logger"

    zigotoo.page_animal:
        class: AppBundle\Service\PageAnimalService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:PageAnimalBranch')"
            - "@file_locator"

    zigotoo.time:
        class: AppBundle\Service\TimeService

    zigotoo.twig.extension:
        class: AppBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }

    zigotoo.doctrine.id_generation_subscriber:
        class: AppBundle\Entity\PersistableDoctrineEventSubscriber
        arguments:
            - "@zigotoo.time"
        tags:
            - { name: doctrine.event_subscriber }
